name: Rasa Train Test Workflow

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  training-testing:
    name: Rasa Training and Testing GHA
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: RTTG Action Step
        id: action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          cross_validation: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Output Test Report
        run: |
          echo "Test Report is as follows:"
          echo ${{ steps.action.outputs.report }}
    
